services:
  web:
    container_name: web
    build:
      context: .
    env_file:
      - ./.env
    ports:
      - 8000:8000
    volumes:
      - .:/src
    depends_on:
      - database
    networks:
      - app_network

  database:
    image: postgres:latest
    container_name: database
    environment:
      - POSTGRES_DB=db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app_network

  redis:
    image: redis:alpine
    container_name: redis
    restart: always
    ports:
      - "16379:6379"
    networks:
      - app_network

  celery:
    build: .
    container_name: celery_worker
    command: celery -A HHanalyzer worker --loglevel=info
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
    volumes:
      - .:/app
    depends_on:
      - redis
      - web
    networks:
      - app_network

  celery-beat:
    build: .
    container_name: celery_beat
    command: celery -A HHanalyzer beat --loglevel=info
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
    volumes:
      - .:/app
    depends_on:
      - redis
      - celery
    networks:
      - app_network

networks:
  app_network:
    driver: bridge

volumes:
  postgres_data:
