services:
  web:
    container_name: web
    build:
      context: .
    env_file:
      - ./.env
    ports:
      - 8000:8000
    volumes:
      - .:/src
    depends_on:
      - database
    networks:
      - app_network

  database:
    image: postgres:latest
    container_name: database
    environment:
      - POSTGRES_DB=db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app_network

networks:
  app_network:
    driver: bridge

volumes:
  postgres_data:
