# Generated by Django 5.1.7 on 2025-03-06 22:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Название')),
                ('search_query', models.CharField(max_length=255, verbose_name='Параметр поиска')),
            ],
            options={
                'verbose_name': 'Профессия',
                'verbose_name_plural': 'Профессии',
            },
        ),
        migrations.CreateModel(
            name='VacancyKeywords',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Ключевой навык',
                'verbose_name_plural': 'Ключевые навыки',
            },
        ),
        migrations.CreateModel(
            name='Vacancy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vacancy_id', models.IntegerField(verbose_name='ID вакансии')),
                ('title', models.CharField(max_length=100, verbose_name='Название вакансии')),
                ('published_at', models.DateField(verbose_name='Дата публикации')),
                ('json_data', models.JSONField(verbose_name='Данные в json')),
                ('profession', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vacancies', to='skills_stats.profession', verbose_name='Профессия')),
                ('key_skills', models.ManyToManyField(related_name='vacancies', to='skills_stats.vacancykeywords', verbose_name='Ключевые навыки')),
            ],
            options={
                'verbose_name': 'Вакансия',
                'verbose_name_plural': 'Вакансии',
            },
        ),
    ]
